# Generated by Django 3.2 on 2021-11-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(default='Неизвестен', max_length=32, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Образование'),
        ),
    ]
