# Generated by Django 3.2 on 2021-12-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('url', models.URLField(verbose_name='URL')),
                ('registered_in', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
    ]
